title: Landing Page
email: lukas@himsel.me
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://landing-page.himsel.me"
login_url: "https://app.landing-page.himsel.me/login"
register_url: "https://app.landing-page.himsel.me/register"
company: Landing Page
street: 123 Main Street
city: 12345 Anytown
hrb: HRB 12345
court: Amtsgericht Musterstadt
director: Lukas Himsel
email: info@example.com

collections:
  authors:
    title: Authors
    output: true
    permalink: "/about/:title.html"
  posts:
    title: Posts
    output: true
    permalink: /:year/:month/:day/:title:output_ext
  features:
    title: Features
    output: false
exclude:
  - "jekyll_runner"
